### ISSUE TITLE
Create a Todo List

### ISSUE THREAD

**Issue by abdelhak-ihadjadene** [MicroClub-USTHB/Hacktoberfest-2k20#6]
In this is mini project, you are invited to create a To-do List using either Vanilla Js or React , we leave the design up to your creativity, but the app must contain some features.
- [ ] Create a single page todo interface with an input, and the list of todos
- [ ] make each todo able to be toggled as finished, each finished todo will be moved into the "finished" category
- [ ] a todo should display the task and the date of creation, if finished and moved in "finished" category, it should also display the date when it was finished
- [ ] Saved todos in localstorage and load them when page loads
- [ ] OPTION: create a filter setting, to filter the todos by certain constraint like date creation ect.

- [ ] OPTION: add priorities to todos
- [ ] OPTION: add a color picker in creation (pick a color for each todo), if no color is picked choose random one
- [ ] OPTION: save todos in a Database

**Comment by sarita1124** [comment]
Hi, can I work on this issue?

**Comment by IndigoWizard** [comment]
@chinmaym07 this is the main issue with that previous task (the "reuse-2" will be deleted/changed)

**Comment by IndigoWizard** [comment]
@sarita1124 Yes, you've assigned!
